### ISSUE TITLE
Presents on self.window.rootViewController gets error

### ISSUE THREAD

**Issue by khalilleo** [Codigami/CFAlertViewController#1]
Gets error said 

-[__NSCFBoolean length]: unrecognized selector sent to instance  xxxx

Not sure what goes wrong

**Comment by khalilleo** [comment]
hmmm it seems some other part of my code have errors

**Comment by vinayak-codigami** [comment]
Is the issue fixed?

**Comment by khalilleo** [comment]
sadly no

**Comment by shardul89** [comment]
@khalilleo as this thread is dead since long I am closing it. If you are still facing the same issue feel free to create a new issue.
