### ISSUE TITLE
Swift 4 warnings

### ISSUE THREAD

**Issue by dtomicAZ** [Codigami/CFAlertViewController#11]
### Issue Info

 Info                          | Value                               |
-------------------------------|-------------------------------------|
 Platform Name                 | ios
 Platform Version              | 11.0
 CFAlertViewController Version | 232
 Integration Method            | manually
 Xcode Version                 | Xcode 9.0
 Repro rate                    | all the time 

### Issue Description and Steps

I have plenty of this warnings in swift 4:
When calling this function in Swift 4 or later, you must pass a '()' tuple; did you mean for the input type to be '()'?

It would be great if you can solve that, thanks.

**Comment by shardul89** [comment]
@dtomicAZ thanks for bringing this into our notice. We have made this library Swift 4 compatible and I am planning to release it within 1-2 days. Just documentation update is pending. I have merged swift 4 changes into develop branch. Can you please fetch the code from develop branch and check into your project that your warning issue is fixed or not.

Feel free to ask any question if you have any doubts.

**Comment by dtomicAZ** [comment]
@shardul89 
HI, I checked this, and for my swift 4 project there is no warnings or errors.

But for my swift 3.2 project I got this error:

Argument labels '(rawValue:)' do not match any available overloads:
self.tableViewLeadingConstraint?.priority = UILayoutPriority(rawValue: 749)

If I modify that line like this than error is gone:
self.tableViewLeadingConstraint?.priority = UILayoutPriority(749)

Is there a way to this library be compatible for swift 3.2 and swift 4, or there should be two versions of CFAlertViewController, one for 3.2 and second for 4 ?

**Comment by Huddie** [comment]
+1
Swift 3.2 error

**Comment by shardul89** [comment]
@dtomicAZ @Huddie If you are using it through pod than you need to set swift language version to `Swift 4.0` in build settings of CFAlertViewController target inside Pods and recompile your project again. Let me know if the issue still persists. 
Here is the reference image:
![screen shot 2017-09-29 at 10 19 46 am](https://user-images.githubusercontent.com/4860897/31001252-0bc49b38-a500-11e7-81c9-be602db2c5e6.png)
