### ISSUE TITLE
Disable background tap to dismiss

### ISSUE THREAD

**Issue by rjpalermo1** [Codigami/CFAlertViewController#3]
Would be good for future users to know in your documentation they can:

`alert.shouldDismissOnBackgroundTap = NO;`

to disable the default behavior allowing background tap to dismiss.

**Comment by shardul89** [comment]
@rjpalermo1 thank you for the suggestion. We will update the documentation soon.

**Comment by shardul89** [comment]
@rjpalermo1 we have updated our library with cool new features and have also updated the documentation with it, which also covers use case of **shouldDismissOnBackgroundTap** property.
Thank you so much :)
