### ISSUE TITLE
Scroll when keyboard up for input either for textfield/textview?

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [Codigami/CFAlertViewController#5]

**Comment by shardul89** [comment]
@Rashesh-Bosamiya can you please explain the problem in detail to better understand the cause of this issue. What exactly you are trying to do and what you are expecting from the library and what is the current output that you are getting. You can attach screenshots also :)

**Comment by Rashesh-Bosamiya** [comment]
The output that I'm expecting is, an alertViewController with following UIView (screenshot).

![screen shot 2017-03-20 at 8 41 21 pm](https://cloud.githubusercontent.com/assets/19154948/24106372/a9be6098-0dad-11e7-8fac-3514bd88e44d.png)

Now, when keyboard is up for textView, AlertController should scroll up if textView is behind keyboard.

**Comment by shardul89** [comment]
@Rashesh-Bosamiya the thing that you are explaining is already represented in Demo project. Can you please share the code snippet for your problem?
