### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by naeemshaikh90** [Codigami/CFAlertViewController#6]
![screen shot 2017-03-21 at 2 59 54 pm](https://cloud.githubusercontent.com/assets/10736853/24141237/e361414e-0e48-11e7-98ec-210d8721da0c.png)

**Comment by naeemshaikh90** [comment]
Hey @Codigami @shardul89 nic lib👌.
Please fix this before I can merge you lib to `awesome-ios`.😀
https://github.com/vsouza/awesome-ios/pull/1577

**Comment by shardul89** [comment]
@naeemshaikh90 I have updated the CFAlertViewController git description. Thanks for pointing it out. It will be awesome to be part of awesome-ios. Do let me know if you need any other help to get this done.
