### ISSUE TITLE
Current version leaks in several places when alert is shown

### ISSUE THREAD

**Issue by Solublepeter** [Codigami/CFAlertViewController#7]
iOS 10.3 on simulated iPhone 7 plus or real iPhone 6S
Xcode 8.3
repro 100%

Observed when the library was integrated into my code, but you can see this easily in the demo- as follows:

Download current .ZIP version, and tap CFAlertViewControllerDemo.xcodeproj
Profile the app in Leaks mode
Tap "Show" in the app, without changing any switches.
Observe a leak every time

Trace file is too large to upload

**Comment by Solublepeter** [comment]
iOS 10.3 on simulated iPhone 7 plus
Xcode 8.3

Just
1. Download current .ZIP version, and tap CFAlertViewControllerDemo.xcodeproj
2. Profile the app in leaks mode
3. Tap "Show", without changing any switches

Trace file is too large to upload

**Comment by shardul89** [comment]
@chefren thanks for the fix. @Solublepeter I am closing this issue as we have fixed it. Feel free to reopen this issue if it is still showing leaks.
