### ISSUE TITLE
Warning "incompatible pointer to integer" in CustomFooterView.m

### ISSUE THREAD

**Issue by Solublepeter** [Codigami/CFAlertViewController#8]
Xcode 8.3, iOS 10.3, simulator

On compilation, get a warning in CustomFooterView.m:

warning reads:
" Incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'UIView * _Nullable'"

from this line:
// Update Header Display State
    self.shouldDisplayHeader = self.alertController.headerView;

**Comment by shardul89** [comment]
@Solublepeter we have fixed this warning in the latest release. Thanks for the feedback.
