### ISSUE TITLE
Wrong tutorial on Swift 3 

### ISSUE THREAD

**Issue by alberttai1** [Codigami/CFAlertViewController#9]
Initializer is CFAlertViewController.alertController(parameters) rather than CFAlertViewController(parameters)

Same with defaultAction which is CFAlertAction.action(parameters) rather than CFAlertAction(parameters)

**Comment by shardul89** [comment]
@alberttai1 I have fixed the initialiser methods. Thanks for your valuable feedback. Lets make this library even more useful for all of us.

Latest Release : https://github.com/Codigami/CFAlertViewController/releases/tag/v2.3
